### ISSUE TITLE
Ability to work with local sites

### ISSUE THREAD

**Issue by Eduardoveras** [ezarko/docker-harp#1]
i have looked but cant find the way to use this with a local folder, it only works with github repos, does this functionality exist?

**Comment by ezarko** [comment]
@Eduardoveras Sorry for the delay in responding ... I must have missed the notification and have just seen this.  I am not sure what you mean.  Once you have the image (via `docker pull` or `docker build`) you can run the various commands as in the readme.  The critical thing is that you must map a host os directory/folder where your application is located into the docker container guest os as the volume `/myproject`.  For instance `docker run --rm -v .:/myproject harp init` is equivalent to `harp init` with a locally installed node/harp.

```
docker run [      OPTIONS       ] IMAGE [COMMAND] [ARG...]
docker run  --rm -v .:/myproject  harp   init

      --rm                Automatically remove the container when it exits
  -v, --volume list       Bind mount a volume
```

Does this make sense?
